version: '3'
services:
  web:
    image: nginx
    volumes:
      - "./:/var/www"
      - ".docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    links:
      - php-fpm
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: default
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  php-fpm:
    build: .docker/php-fpm
    volumes:
      - "./:/var/www"
    links:
      - db
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 5601:5601
    volumes:
      - .docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elastic
volumes:
  db-data:
  esdata: